### ISSUE TITLE
Issue with SIGCHLD handling

### ISSUE THREAD

**Issue by chrisgilbert** [signalfx/signalfx-collectd-plugin#71]
We are seeing an intermittent issue on some of our agents, where the signalfx-metadata plugin never sends data back correctly.  Strangely, it doesn't seem to happen all the time, and sometimes a new server starts it without issues.  It only affects this one plugin:
```
[2019-01-04 11:30:25] signalfx-metadata: executing SIGCHLD workaround
[2019-01-04 11:30:25] dogstatsd: plugin init <collectd_dogstatsd.DogstatsDConfig object at 0x1db5110>
[2019-01-04 11:30:25] dogstatsd: dogstatsd port listening not enabled
[2019-01-04 11:30:25] docker : Collecting stats about Docker containers from unix://var/run/docker.sock (API version 1.38; timeout: 3s).
[2019-01-04 11:30:25] check_capability: unsupported capability implementation. Some plugin(s) may require elevated privileges to work properly.
[2019-01-04 11:30:25] check_capability: unsupported capability implementation. Some plugin(s) may require elevated privileges to work properly.
[2019-01-04 11:30:25] Initialization complete, entering read-loop.
[2019-01-04 11:30:25] signalfx-metadata: found host ip-172-27-86-15.ec2.internal
[2019-01-04 11:30:25] Unhandled python exception in read callback: IOError: [Errno 10] No child processes
[2019-01-04 11:30:25] Traceback (most recent call last):
[2019-01-04 11:30:25]   File "/opt/signalfx-collectd-plugin/signalfx_metadata.py", line 976, in send
    send_datapoints()
[2019-01-04 11:30:25]   File "/opt/signalfx-collectd-plugin/signalfx_metadata.py", line 1505, in send_datapoints
    PLUGIN_UPTIME, get_linux_version(), platform.release(),
[2019-01-04 11:30:25]   File "/usr/lib64/python2.6/platform.py", line 1291, in release
    return uname()[2]
[2019-01-04 11:30:25]   File "/usr/lib64/python2.6/platform.py", line 1239, in uname
    processor = _syscmd_uname('-p','')
[2019-01-04 11:30:25]   File "/usr/lib64/python2.6/platform.py", line 996, in _syscmd_uname
    rc = f.close()
[2019-01-04 11:30:25] read-function of plugin `python.signalfx_metadata' failed. Will suspend it for 20.000 seconds.
```
collectd keeps suspending the plugin for longer and longer periods of time when this happens.  I can't find evidence that it recovers afterwards.

Here's the line it's occuring:
https://github.com/signalfx/signalfx-collectd-plugin/blob/e2635bd4b1ca6c900a393fab26f785c9165abdf3/src/signalfx_metadata.py#L1505

From googling, it seems there is already code to try to fix this issue - and I can see it being executed with the line `signalfx-metadata: executing SIGCHLD workaround` in the log.  I am wondering if there's some kind of race condition here, and it's not executing that code early enough for the plugin to be inited properly, or not executing it in another thread or something like that.

**Comment by chrisgilbert** [comment]
I've found that this instance _has_ eventually recovered - about an hour and a half later it ran the plugin successfully and collected the metadata for the first time.  Since then it seems to have been fine.  So it looks like it's only happening until it sucessfully runs the first time, so it's perhaps some kind of initialization problem.
```
[2019-01-04 12:12:45] IOError: [Errno 10] No child processes
[2019-01-04 12:12:45] read-function of plugin `python.signalfx_metadata' failed. Will suspend it for 2560.000 seconds.
....
....
[2019-01-04 12:55:26] signalfx-metadata: adding small dither of 52 seconds before sending notifications
[2019-01-04 12:56:25] signalfx-metadata: is an aws box
[2019-01-04 12:56:25] Notification: severity = OKAY, host = ip-172-27-86-15.ec2.internal, plugin = signalfx-metadata, plugin_instance = host_machine, ty
pe = objects, type_instance = host-meta-data, message = x86_64
[2019-01-04 12:56:25] Notification: severity = OKAY, host = ip-172-27-86-15.ec2.internal, plugin = signalfx-metadata, plugin_instance = host_kernel_rele
ase, type = objects, type_instance = host-meta-data, message = 4.14.77-69.57.amzn1.x86_64
........
........
[2019-01-04 12:57:36] Notification: severity = OKAY, host = ip-172-27-86-15.ec2.internal, plugin = signalfx-metadata, plugin_instance = host_mem_total, type = objects, type_instance = host-meta-data, message = 7809804
[2019-01-04 12:57:36] signalfx-metadata: till next metadata 3658.99999714 seconds
```

**Comment by keitwb** [comment]
Thanks for reporting this @chrisgilbert.  Yes, I also suspect it is a race condition between the setting of the workaround signal handler and the call to `platform.release()` that ultimately was creating the subprocess and waiting for it.  I'm pretty sure the workaround function returns before the function that is raising the error gets called, but perhaps that is something asynchronous going on in Python/Linux kernel that causes it to race.  If you are getting the exception multiple times back-to-back then probably something else is going on since there would be plenty of time between the resetting of the signal handler and a second attempt at calling the read callback (which is where the exception occurs).  I have no idea what it might be in that case.

We have actually moved all of the host metadata collection out of this plugin and into the [host-metadata monitor in the Smart Agent](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/host-metadata.md) and now only do metric aggregation in this signalfx-metadata collectd python plugin, so this is a moot point if you are using the Smart Agent.  If this is a bothersome enough issue for you, would you be willing to upgrade to the Smart Agent?

**Comment by atoulme** [comment]
Closing as per recommendation to use the Smart agent. Please comment if this issue needs to be reopened.
